### ISSUE TITLE
HysteresisDriver() Ubermag

### ISSUE THREAD

**Issue by ahsu83** [ubermag/workshop#12]
Hi Ubermag team,

Can we use HysteresisDriver() in ubermag like the one used in oommfc standard problem 1 on nano hub website? Or if there is another driver in ubremag? I tried HysteresisDriver() in ubremag but it says module 'oommfc' has no attribute 'HysteresisDriver'.

**Comment by marijanbeg** [comment]
Hi @ahsu83,

thank you for your question. HysteresisDriver is not implemented explicitly. Since Ubermag exposes OOMMF simulations to Python, you can run hysteresis simulations as a simple `for` loop. An example would be:

```
mz = []
B_list = [0.0, 0.1, 0.2, 0.3,...]
for B in B_list:
    system.energy.zeeman.H = (0, 0, B/mm.consts.mu0)
    md.drive(system)
    mz.append(system.m.average[2])
```

I hope this answers your question. I am going to address hysteresis simulations in the next live workshop session. Please feel free to raise a new issue if there are any further questions you might have.

**Comment by ahsu83** [comment]
Thanks for the answer
