### ISSUE TITLE
Test Ubermag failures

### ISSUE THREAD

**Issue by p-brane** [ubermag/workshop#33]
The `python -c "import ubermag; ubermag.test()"` of the installation yields 79 errors. 

It looks like the Tcl 8.6 version included with ubermag is some how different than the Tcl 8.6.10 installed with oommf for the first tutorial. Ubermag reports that tcl 8.6.9 was found and version 8.6.10 is required. The Tcl I installed with oommf is 8.6.10. It's more likely that a script couldn't find something and went looking for it in the Tcl path installed as part of the oommf install. The same thing happened with python script using the ubermag paths and then on the last trace going off to either the Lyx python path or the PyCellstudio path until I removed the path references in Path, PYTHONHOME, and PYTHONPATH. I removed the oommf tcl path and that cleared some of the errors.

Now there are 68 failures and they are associate with OSError errors about missing oommf, oommfc, and  Docker. I look into that next.

Are there any directions on how to install minconda3 and ubermag on Windows 10 with existing installations of python (Lyx, PyCellStudio), and Tcl with details on how to set environmental and path variables? conda or python seems to want to find modules that are part of other installation and this causes version conflicts and errors. I'd prefer if ubermag had its own environmental variables that could set a specific context for the program(s).

**Comment by catrevil** [comment]
For this ubermag environment, did you make sure to set python to 3.8 when you created it? After this, I would not try to do updates specifically to the ubermag environment install of python, and instead let conda work its dependencies magic when you tell it to `conda update ubermag`. This may be related to your tcl issues. I have 2.0a2 installed which usurps the 2.0a1 installed by ubermag, and this works with no issues

When did you `conda update ubermag` last? I ask this because in the most recent release, the need to install Docker was a result of the fixes implemented by Marijan to overcome the limitations of the Windows OS, and allow for more expansive boundary condition definitions which they had written some time ago (but which do not run in Windows). You’ll have to follow the Docker installation directions on their website for that part.

**Comment by marijanbeg** [comment]
Hi @p-brane, I am sorry you still have problems installing Ubermag.

If you already have Python and OOMMF on you machine, you can install Ubermag and set-up Ubermag by following our "advanced installation" instructions: https://ubermag.readthedocs.io/en/latest/ipynb/advanced-installation.html. You can skip step 1 (since you already have Pyhton) and install Ubermag with `pip`. Then you can set the environment path to `oommf.tcl`.

It is strange conda installation does not cope well with previous installations of Python on your machine, because this is one of its main purposes - create nicely isolated environments to avoid any possible conflicts. But that's software and Windows :/

**Comment by marijanbeg** [comment]
Hi @p-brane, any updates on this issue?

**Comment by p-brane** [comment]
Hi @marijanbeg 
I added the environmental variable OOMMFTCL variable and that help a lot. I only have two failures now! Would you provide some guidance on how to fix them?

```
=========================== short test summary info ===========================
FAILED tests/test_micromagnetictests.py::test_info_file - AssertionError
FAILED tests/test_micromagnetictests.py::test_multiple_drives - AssertionError
= 2 failed, 296 passed, 1 skipped, 5 deselected, 34 warnings in 895.20s (0:14:55)
```

Part of the first error message from __init__.py is shown below.

```
        assert info['drive_number'] == 1
        assert re.findall(r'\d{4}-\d{2}-\d{2}', info['date']) is not []
        assert re.findall(r'\d{2}:\d{2}-\d{2}', info['time']) is not []
>       assert info['driver'] == 'MinDriver'
E       AssertionError

..\..\..\.conda\envs\ubermag\Lib\site-packages\micromagnetictests\calculatortests\info_file.py:75: AssertionError
```

The second error message is 
```
>       assert len(os.listdir(name)) == 5
E       AssertionError

..\..\..\.conda\envs\ubermag\Lib\site-packages\micromagnetictests\calculatortests\multiple_drives.py:54: AssertionError
---------------------------- Captured stdout call -----------------------------
Running OOMMF (TclOOMMFRunner) [2020/07/09 01:02]... Start: "C:/Users/<user directory>/ubermag/test-ubermag/multiple_drives/drive-10/multiple_drives.mif"

Options: -exitondone 1 -threads 4

Boxsi version 2.0a2

```

**Comment by marijanbeg** [comment]
Hi @p-brane, great, thank you for letting us know. Are you running tests in a clean directory?

**Comment by p-brane** [comment]
Hi @marijanbeg 
I deleted all the files and directors from past tests in my test directly and that fixed it. It ran 298 tests with no errors!!!
==== 298 passed, 1 skipped, 5 deselected, 34 warnings in 905.62s (0:15:05) ====
The Jupyter notobook runs so I'll start up the second session video this afternoon. Thank you all the help.

**Comment by marijanbeg** [comment]
Amazing. Thank you for letting us know.

I am going to close this issue now, but as always, if you need any other support, please let us know :)
