### ISSUE TITLE
Demag energy

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#60]
Dear sir
I have a confusion that when, mm.Demag() should take in account for simulation and when it should not be use. Actually from the my own experimental parameter,i want to know whether skyrmion like structure exists or not because experimentally i am getting Topological Hall. When i simulate with demag, i end up with vortex like structure but when i did not use vortex is not there. So i how can i verify that my experimental result with or without demag.

**Comment by marijanbeg** [comment]
Hi @gaurav123shukla, thank you for your question. Generally demagnetisation energy is always present in the sample and it should always be included in simulations. However, because demag is computationally very expensive (and difficult to compute), there are certain cases when its effect can be neglected. So, if adding demag to your simulation changes the results, this means that ignoring demag is not justified.
