### ISSUE TITLE
lastomffile not found

### ISSUE THREAD

**Issue by mrtalkingbadger** [ubermag/workshop#63]
Hello,
one of my ubermag scripts throws the following error when i drive the system:

"
Traceback (most recent call last):
  File "uberamag_nucleation.py", line 52, in <module>
    md.drive(system)
  File ".../.conda/envs/UBERMAG_ENV/lib/python3.8/site-packages/oommfc/drivers/driver.py", line 198, in drive
    lastomffile = sorted(omffiles)[-1]
IndexError: list index out of range
"

Does anyone has an idea where this could come from? it is a short script (initalizing FM state in a disk and relaxing)
 

Best,
Thomas

**Comment by marijanbeg** [comment]
Hi @mrtalkingbadger, this error usually means that OOMMF run failed and OOMMF did not output any files due to an error. If you get this error for all Ubermag runs, then probably Ubermag is not installed properly. If you get it only for some runs, then please send me the script, so I can explore where the error might have occurred.

**Comment by marijanbeg** [comment]
Hi @mrtalkingbadger, is this problem resolved? If not, please feel free to reopen this issue.
