### ISSUE TITLE
Systematic study of variation of skyrmion velocity with skyrmion size

### ISSUE THREAD

**Issue by Ayers6991** [ubermag/workshop#69]
Hello,
How can I study systematically the variation of skyrmion
velocity with skyrmion size?
Thanks.

**Comment by marijanbeg** [comment]
Hi @Ayers6991, thank you for your question. I am afraid your question is too general for me to answer it specifically. However, I can give you a suggestion...

In order to systematically study any parameter variation, you would need to make a `for`-loop which iterates through the parameter values you are interested in. Then you store the result in a list, for example:

```
my_results = []
for A in [1e-12, 1.2e-12, 1.4e-12]:
    # here you assemble the system and drive it
    my_results.append(the_result)

# At this point you should have the values you are interested in
```
If this is not the answer you were expecting, please feel free to reopen this issue.
