### ISSUE TITLE
AttributeError: Object has no attribute k3d_vector.

### ISSUE THREAD

**Issue by Mishrakishan** [ubermag/workshop#87]
Hi @marijanbeg. Thank you for the amazing ubermag workshop. It's very well put. 

I have installed ubermag as been guided and everything worked out fine. I was executing the 'first_ubermag_simulation' file. Everything ran smoothly but there was an error on cell:

`system.m.plane('z').k3d_vector(headsize=10)`

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[26], line 1
> ----> 1 system.m.plane('z').k3d_vector(headsize=10)
> 
> File ~/opt/anaconda3/envs/ubermag/lib/python3.10/site-packages/discretisedfield/field.py:842, in Field.__getattr__(self, attr)
>     840 else:
>     841     msg = f"Object has no attribute {attr}."
> --> 842     raise AttributeError(msg)
> 
> AttributeError: Object has no attribute k3d_vector.

**Comment by lang-m** [comment]
Hi @Mishrakishan, since recording the workshop parts of the interface in Ubermag have changed, e.g. you now use `system.m.plane('z').k3d.vector(headsize=10)` to get the 3d plot. You can find up-to-date information (including updated versions of the notebooks from this workshop) on our website https://ubermag.github.io, e.g. for plotting with k3d refer to this page: https://ubermag.github.io/documentation/notebooks/discretisedfield/field-k3d-visualisation.html
